# Generated by Django 5.1.2 on 2024-10-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desc',
            new_name='description',
        ),
    ]
